export const Configs = {
    EXPRESS_PORT: 35000,
    HOST: "http://127.0.0.1",

    // PRODUCT REQUEST CONSTANTS
    PRODUCT_REQUEST_TIMEOUT: 7000,
    PRODUCT_REQUEST_FAIL_TIMES: 3,
    MAX_PROXY_REQUESTS_COUNT: 30,
    PROXY_REQUEST_INTERVAL: 15000,
}
